import type { Metadata } from "next";
import { Geist, Geist_Mono, Black_Han_Sans } from "next/font/google";
import "./globals.css";
import FirebaseInitializer from "./_lib/firebase/FirebaseInitializer";
import AuthProvider from "./_lib/firebase/FirebaseAuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const blackHanSans = Black_Han_Sans({
  variable: "--font-black-han-sans",
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="apple-touch-icon" href="/icon.png"></link>
        <meta name="theme-color" content="#f7f7f7" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${blackHanSans.variable}`}
      >
        <FirebaseInitializer>
          <AuthProvider loginComponent={undefined}>{children}</AuthProvider>
        </FirebaseInitializer>
      </body>
    </html>
  );
}
